### ISSUE TITLE
Upgrade from 3.5 to 4.x fails 

### ISSUE THREAD

**Issue by Ruudje007** [zwave-js/zwavejs2mqtt#1154]
Hi All,

The moment i upgrade my docker container from 3.5 to 4.x i receive errors

```
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit

(Use `node --trace-warnings ...` to show where the warning was created)

(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit

(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

Within the control panel i see in the right top of my screen the following error 
```
Driver: this.container.getLogger is not a function

```

**Comment by robertsLando** [comment]
How are you starting the application?

**Comment by Ruudje007** [comment]
Hi Roberts,

This is my config

```YAML

    zwavejs2mqtt:
        container_name: zwavejs2mqtt
        image: zwavejs/zwavejs2mqtt:3.5.0
        restart: always
        tty: true
        stop_signal: SIGINT
        environment:
            - SESSION_SECRET=xxxxxxxx
            - TZ=Europe/Amsterdam
        devices:
            - '/dev/ttyACM0:/dev/ttyACM0'
        volumes:
            - type: bind
              source: ./store
              target: /usr/src/app/store
            - type: volume
              source: zwavejs
              target: /usr/src/app/node_modules/@zwave-js/config
        ports:
            - '8091:8091' # port for web interface
            - '3000:3000' # port for zwave-js websocket server

```
