### ISSUE TITLE
[bug] MQTT client is diconnected 

### ISSUE THREAD

**Issue by bdbogjoe** [zwave-js/zwavejs2mqtt#1314]
### Version

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.5.2

### Describe the bug

with version 4.5.2 the MQTT client try always to reconnect, seems mosquitto server reject connection
Note : I'm using Mosquitto 2.0.10

Works fine with 4.5.1

maybe releated to https://github.com/zwave-js/zwavejs2mqtt/commit/a9d577c0459f3be2df25749b9cd8269f8f5d1909

here the logs : 

```
zwavejs2mqtt    | 2021-06-08 21:08:49.422 INFO MQTT: MQTT client closed
zwavejs2mqtt    | 2021-06-08 21:08:50.423 INFO MQTT: MQTT client reconnecting
zwavejs2mqtt    | 2021-06-08 21:08:52.543 INFO MQTT: MQTT client closed
zwavejs2mqtt    | 2021-06-08 21:08:53.543 INFO MQTT: MQTT client reconnecting
zwavejs2mqtt    | 2021-06-08 21:08:55.663 INFO MQTT: MQTT client closed
zwavejs2mqtt    | 2021-06-08 21:08:56.664 INFO MQTT: MQTT client reconnecting
zwavejs2mqtt    | 2021-06-08 21:08:58.782 INFO MQTT: MQTT client closed
zwavejs2mqtt    | 2021-06-08 21:08:59.783 INFO MQTT: MQTT client reconnecting
zwavejs2mqtt    | 2021-06-08 21:09:01.912 INFO MQTT: MQTT client closed
zwavejs2mqtt    | 2021-06-08 21:09:02.913 INFO MQTT: MQTT client reconnecting
zwavejs2mqtt    | 2021-06-08 21:09:05.022 INFO MQTT: MQTT client closed
zwavejs2mqtt    | 2021-06-08 21:09:06.022 INFO MQTT: MQTT client reconnecting
zwavejs2mqtt    | 2021-06-08 21:09:08.143 INFO MQTT: MQTT client closed
zwavejs2mqtt    | 2021-06-08 21:09:09.143 INFO MQTT: MQTT client reconnecting
zwavejs2mqtt    | 2021-06-08 21:09:11.263 INFO MQTT: MQTT client closed
zwavejs2mqtt    | 2021-06-08 21:09:12.263 INFO MQTT: MQTT client reconnecting
zwavejs2mqtt    | 2021-06-08 21:09:14.382 INFO MQTT: MQTT client closed
zwavejs2mqtt    | 2021-06-08 21:09:15.382 INFO MQTT: MQTT client reconnecting
zwavejs2mqtt    | 2021-06-08 21:09:17.503 INFO MQTT: MQTT client closed
zwavejs2mqtt    | 2021-06-08 21:09:18.504 INFO MQTT: MQTT client reconnecting
```

**Comment by robertsLando** [comment]
@bdbogjoe could you try to use `master` tag please and report me if it's working with that?

**Comment by bdbogjoe** [comment]
here my docker-compose file

```
version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:4.5.1
    restart: always
    tty: true
    stop_signal: SIGINT
    networks:
      - mqtt
    devices:
      - '/dev/ttyACM10:/dev/ttyACM10'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zwave/store:/usr/src/app/store
    ports:
      - '8091:8091'

networks:
  mqtt:
```
