### ISSUE TITLE
[feat] Be able to make a switch come across to hass as a light

### ISSUE THREAD

**Issue by DTTerastar** [zwave-js/zwavejs2mqtt#1468]
**Is your feature request related to a problem? Please describe.**

Light switches are currently always exposed as switches and there doesn't seem to be a configuration option to expose them as light.* entities.

**Describe the solution you'd like**

Something in the configuration of a switch that says "this is a light" so you can send it across to hass correctly (instead of some hacky yaml to make a duplicate entity but with the correct domain)

**Describe alternatives you've considered**

I am aware of the yaml to make an additional fake light out of a switch but adding stuff via yaml always leads to wonky startup behavior, no area, etc.  I think we're all trying to get away from that (I hope at least).

**Additional context**

n/a

**Comment by robertsLando** [comment]
Did you try to add a device class to it in gateway values table?

**Comment by DTTerastar** [comment]
I have tried, but it doesn't allow it to change and based on this line from the documentation that only works for sensors:

> Device Class: If the value is a multilevel sensor, a binary sensor or a meter you can set a custom device_class to use with home assistant discovery. Check sensor and binary sensor

**Comment by robertsLando** [comment]
The only alternative would be to add a custom implementation in customDevices or devices.js

**Comment by CWSpear** [comment]
Along these lines, I have the same physical device being used for fans, switches and lights. So it'd be nice to override that `device_class` arbitrarily on a per-device level.

I'm specifically using the websockets API to sync devices, if that makes a difference.

**Comment by DTTerastar** [comment]
> Along these lines, I have the same type of physical device being used for fans, switches and lights. So it'd be nice to override that `device_class` arbitrarily on a per-device level.
> 
> I'm specifically using the websockets API to sync devices, if that makes a difference.

Customize.yaml can fix that.  There is no fix for the wrong domain tho...

**Comment by CWSpear** [comment]
Er, I did mean `domain`.

Ok, shucks... I guess `template`-workarounds for now.

**Comment by sotatech** [comment]
Have you tried the HA light switch integration: [https://www.home-assistant.io/integrations/light.switch/](url) That should achieve the desired results.

**Comment by scyto** [comment]
this is a dupe of a very old issue (i opened and closed)  light.switch is the right way to solve this and works, her is an example

```
light:
    - platform: switch
      name: Christmas Tree
      entity_id: switch.livingroom_outletpigtail_switch
    - platform: switch
      name: Back Balcony
      entity_id: switch.backbalcony_lights_switch
    - platform: switch
      name: Back Porch
      entity_id: switch.backporch_lights_switch
    - platform: switch
      name: Front Balcony
      entity_id: switch.frontbalcony_lights_switch
    - platform: switch
      name: Front Porch
      entity_id: switch.frontporch_lights_switch
    - platform: switch
      name: Study Porch
      entity_id: switch.studyporch_lights_switch
    - platform: switch
      name: Guest Lamp
      entity_id: switch.guestbedroom_outlet_switch_1
    - platform: switch
      name: Tetris Light
      entity_id: switch.masterbedroom_outlet_switch
```
