### ISSUE TITLE
Error: EINVAL: invalid argument, fsync

### ISSUE THREAD

**Issue by robcos** [zwave-js/zwavejs2mqtt#1668]
EDIT: zwavejs/zwavejs2mqtt:5.4.0 on Docker version 19.03.14 on VirtualBox

Was working fine. I upgraded because Homeassistant needed a never version and it now crashes at startup after a few seconds.

```
2021-09-06 22:49:35.556 INFO ZWAVE: Node 1 ready: AEON Labs - ZW090 (Z‐Stick Gen5 USB Controller)
2021-09-06 22:49:35.625 INFO ZWAVE: Node 8 is asleep
2021-09-06 22:49:35.635 INFO ZWAVE-SERVER: ZwaveJS server listening on port 3000
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: EINVAL: invalid argument, fsync



```

**Comment by robertsLando** [comment]
@AlCalzone I don't use `fsync`, maybe something related to the config db?

**Comment by AlCalzone** [comment]
That's the value DB, which uses `fsync` to ensure atomic operations. I just love how those low level errors don't include any information what went wrong 🤷🏻‍♂️

**Comment by AlCalzone** [comment]
Looks terribly like [this issue](https://github.com/louischatriot/nedb/issues/407). @robcos anything special about your setup?

**Comment by robcos** [comment]
I'm running on docker, inside virtualbox, on os x. Have tried to completely whack my container (and the store folder, including settings) but this keeps coming up. Is there some other "storage" that zwavejs2mqtt may be using?

**Comment by robertsLando** [comment]
> I'm running on docker, inside virtualbox, on os x

Cool 🤣 Do you have a docker-compose file?

**Comment by robcos** [comment]
From what I can see, this seems to be affecting users on Mac filesystems but what happened that made it stop working?

In any case, putting the store folder onto a docker volume fixed it:

```
version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - NETWORK_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - TZ=Europe/London
    devices:
      - '/dev/ttyS1:/dev/ttyS1'
    volumes:
      #- ./store:/usr/src/app/store #<--- It used to work with this earlier but not anymore
      - zwavejs2mqtt_store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3001:3000' # port for zwave-js websocket server
volumes:
  zwavejs2mqtt_store:
```
