### ISSUE TITLE
[feat] Documentation for docker-compose needs improvement

### ISSUE THREAD

**Issue by rr326** [zwave-js/zwavejs2mqtt#1874]
**Is your feature request related to a problem? Please describe.**
I tried to get zwavjs2mqtt running with home assistant and docker-compose while following the description [here](https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/docker). It didn't work properly. I finally got it working after a lot of trial and error and changing my docker-compose.yml file. 

**Describe the solution you'd like**
I am NOT an expert in docker, docker-compose, but here is what I learned:

This all refers to the `docker-compose.yml` section on [this page](https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/docker)

* First, the link in this line is broken: To run "ZWavejs2Mqtt as a service you can use the docker-compose.yml found here:"
* I don't think you need the networks: -zwave section. In fact, if you have it, I think it means you need to make sure HomeAssistant  and your MQTT broker are  also running in that network, right?
* I think there is a bug in your `volumes` config. In the zwavejs2mqtt section you have a target of `.store` but in the `volumes` below, it is `zwave-config`. They should be the same, right? 
* As far as I can tell, zwavejs2mqtt needs another MQTT service running as a broker, on 1883, right? If so, I kept getting "ECONNREFUSED" from when trying to connect. But I added `network_mode: host` and that worked. (Or perhaps I could have used the zwave network you suggest, but then would have to make sure my broker is in that network, right? 
* Also, this is separate, but it took me a while to realize what Zwavejs2mqtt is and is not. It is NOT just a zwave to mqtt gateway. it is ALSO a config UI. And it is ALSO a zwavejs server! (I had to turn off my own server.) And it is NOT an MQTT broker. I realize this is basically said in the docs, but it is quite confusing, based on the name and how the docs are written. 

**Describe alternatives you've considered**

**Additional context**
Here is my relevant docker-compose.yml. Reminder - I'm not an expert, just a confused follower trying to help others come up to speed.

```
version: '3.4'
services:
  zjs2mqtt:
    container_name: zjs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET="xxx"
      - S2_ACCESS_CONTROL_KEY="xxx" 
      - S2_AUTHENTICATED_KEY="xxx"
      - S2_UNAUTHENTICATED_KEY="xx"
      - S0_LEGACY_KEY="xx"      
      - TZ=America/New_York
    devices:
      - '/dev/ttyACM0:/dev/zwave'
    volumes:
      - ./zwave-config:/usr/src/app/store
    ports:
      - "8091:8091" 
      - "3000:3000" 
    network_mode: host
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ../mosquitto/config:/mosquitto/config/
      - ../mosquitto/data:/mosquitto/data/
      - ../mosquitto/log:/mosquitto/log/
    ports:
      - '1883:1883'
    network_mode: host
    restart: unless-stopped    
volumes:
  zwave-config:
    name: zwave-config        
```
