### ISSUE TITLE
[feat] How can we reset energy meters?

### ISSUE THREAD

**Issue by Swiftnesses** [zwave-js/zwavejs2mqtt#194]
Running latest docker 'dev' version.

Using the old Home Assistant zwave implementation it was possible to reset energy meters (for example, Aeon smart switches) using a service, for example:

```
- action:
  - data:
      node_id: 2
    service: zwave.reset_node_meters
  alias: Reset Home Energy Meter kWh
  condition: []
  id: '1513310745263'
  trigger:
  - event_data: {}
    event_type: ''
    platform: event
```

Is this achievable via zwavejs2mqtt, or on the roadmap?
