### ISSUE TITLE
[question]  Trigger scene with fibaro key fob

### ISSUE THREAD

**Issue by haavardNO** [zwave-js/zwavejs2mqtt#198]
Just starting to play with zwavejs2mqtt, and so far so good.
But I am struggling with some of mye scene controllers. The fibaro key fob includes with no issues. And it creates several devices in Home Assistant. But when I press a button it only changes state once, and stays at that state. Before when I used zwave2mqtt it would jump back to "standby" or inactive, and just get the activated state for a second or so.

Is there something I am missing or is there something wrong here?

**Comment by robertsLando** [comment]
@haavardNO Could you provide some logs? BOth zwavejs and zwavejs2mqtt?

**Comment by haavardNO** [comment]
Yes, I can try.
I can at least pull some logs from the UI of zwavejs2mqtt. How can I get the logs from zwavejs?

**Comment by robertsLando** [comment]
@haavardNO If you are using docker `dev` tag, you will find them in store folder if you enable log to file in settings

**Comment by jcam** [comment]
@haavardNO which version of zwavejs2mqtt are you using?

The best way for now to trigger automations on scene button presses is to read the event bus, rather than reading a state change.
Here is an example of an central scene trigger, using a zooz scene switch:
```
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.outdoor_frontpath_scene_state_001_scene
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.new_state.state == ''3'' }}'
```
