### ISSUE TITLE
[Question] What can be the cause of devices not being found during inclusion?

### ISSUE THREAD

**Issue by Timmiej93** [zwave-js/zwavejs2mqtt#2240]
I'm switching over from running zwavejs2mqtt on a RPi with RaZberry hat to running it on a small Linux PC with the z-wave.me USB (ZMEEUZB1). On the RPi zwavejs2mqtt always worked fine, but getting it all to work together was a nightmare.

Now I'm trying to set up zwavejs2mqtt on the Linux machine. Everything has worked absolutely perfectly, right up until the inclusion of devices. Here's what I did:

- Create section in docker-compose for zwavejs2mqtt and start the container<details>
  <summary>Click to view YAML</summary>

   ```
    zwavejs2mqtt:
        container_name: ZwaveJS2MQTT
        image: zwavejs/zwavejs2mqtt:6.5.0
        restart: always
        tty: true
        stop_signal: SIGINT
        environment:
            - SESSION_SECRET=mysupersecretkey
            - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
            # Uncomment if you want logs time and dates to match your timezone instead of UTC
            # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
            - TZ=Europe/Amsterdam
        networks:
            - docker-lan
        devices:
            # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
            # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
            - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
        volumes:
            - zwave-config:/usr/src/app/store
        ports:
            - '8091:8091' # port for web interface
            - '8092:8092' # port for Z-Wave JS websocket server
   ```
</details>

- Z-Wave settings in zwavejs2mqtt:
   - Serial port: /dev/zwave
   - Generated a random S2/S0 key 4 times
   - AFAIK, other settings shouldn't affect inclusion, if I'm wrong, please correct me.
 
- Updated through the GUI

The usb stick controller shows up in the control panel perfectly fine. Starting an inclusion also works fine. However, I can press the inclusion buttons on my devices as much as I want, nothing happens. Not a single entry is placed in the log either. I tried holding one of the devices right next to the controller, but even then it didn't pick it up.

I'm really wondering if I did something wrong here, or if I received faulty hardware from the box.

Just for my peace of mind: I don't need to separately install zway or some kind of zway server, right? Like I said, getting everything to work on the RPi was an absolute nightmare. One website said to install this, the other to install that, change this, change that, so I never really knew what was required and what didn't do anything.

[zwavejs_2022-02-04.log](https://github.com/zwave-js/zwavejs2mqtt/files/8003403/zwavejs_2022-02-04.log)
