### ISSUE TITLE
[question] Rediscovery of devices after HomeAssistant restart

### ISSUE THREAD

**Issue by raymonvdm** [zwave-js/zwavejs2mqtt#226]
I have switched from zwave2mqtt to zwavejs2mqtt and it is working quite well after some trial and error in the beginning due to my own ignorance but al seems to be running well. There are only some minor issues left, and one larger issue

In the past when i restarted HomeAssistant the Zwave devices where usable as soon as HomeAssistant was started, but now they are only available after saving a setting in zwavejs2mqtt, since it sends a rediscovery and sends all data to the MQTT broker for HomeAssistant to relearn the status of the devices.

I have worked around this issue by enabling Retained Discovery, but i never had this setting enabled in zwave2mqtt

Is it possible that zwave2mqtt was responding to the birth and will messages HomeAssistant was sending on restart?

MQTT settings in HomeAssistant

```
mqtt:
  broker: mqtt.domain.net
  port: 1883
  client_id: home-assistant-1
  username: homeassistant
  password: secret
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
   topic: 'hass/status'
   payload: 'online'
  will_message:
   topic: 'hass/status'
   payload: 'offline'

```
