### ISSUE TITLE
[question]  Are SSL_KEY  SSL_CERTIFICATE implemented for docker?

### ISSUE THREAD

**Issue by asucrews** [zwave-js/zwavejs2mqtt#2465]
No matter how I changed my docker-compose file, I can't seem to get zwave2mqtt to accept the new certs, it just keep making it own. What am i missing.

```
version: '3.7'
services:
  zwave2mqtt:
    container_name: zwave2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=<removed>
      - ZWAVEJS_EXTERNAL_CONFIG='/usr/src/app/store/.config-db'
      - TZ=America/Phoenix
      - SSL_KEY='/opt/ssl/key.pem'
      - SSL_CERTIFICATE='/opt/ssl/cert.pem'
    devices:
      - <removed>:/dev/ttyAMA0'
    volumes:
      - ./store:/usr/src/app/store
      - /opt/ssl/cert.pem:/opt/ssl/cert.pem
      - /opt/ssl/privkey.pem:/opt/ssl/key.pem
    ports:
      - '8091:8091'
      - '3000:3000'
```

```
zwave2mqtt  | 2022-06-13 17:25:17.710 INFO APP: Version: 6.12.0
zwave2mqtt  | 2022-06-13 17:25:17.715 INFO APP: Application path:/usr/src/app
zwave2mqtt  |
zwave2mqtt  |  ______                       _     ___                  _   _
zwave2mqtt  | |___  /                      (_)   |__ \                | | | |
zwave2mqtt  |    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
zwave2mqtt  |   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
zwave2mqtt  |  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
zwave2mqtt  | /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
zwave2mqtt  |                             _/ |                      | |
zwave2mqtt  |                            |__/                       |_|
zwave2mqtt  |
zwave2mqtt  | 2022-06-13 17:25:17.772 WARN STORE: scenes.json not found
zwave2mqtt  | 2022-06-13 17:25:17.795 INFO APP: HTTPS is enabled. Loading cert and keys
zwave2mqtt  | 2022-06-13 17:25:17.798 INFO APP: Cert and key not found in store, generating fresh new ones...
zwave2mqtt  | 2022-06-13 17:25:18.058 INFO APP: New cert and key created
zwave2mqtt  | 2022-06-13 17:25:18.108 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTPS
zwave2mqtt  | 2022-06-13 17:25:18.197 INFO MQTT: Connecting to mqtt://<removed>:8883
zwave2mqtt  | 2022-06-13 17:25:18.320 ERROR MQTT: Mqtt client error getaddrinfo ENOTFOUND mqtts
zwave2mqtt  | Error: getaddrinfo ENOTFOUND mqtts
zwave2mqtt  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26)
zwave2mqtt  | 2022-06-13 17:25:18.323 INFO MQTT: MQTT client offline
zwave2mqtt  | 2022-06-13 17:25:18.324 INFO MQTT: MQTT client closed
zwave2mqtt  | 2022-06-13 17:25:18.351 INFO ZWAVE: Connecting to <removed>

```

**Comment by kpine** [comment]
Remove the quotes around the environment variables. That is causing the files to be named like `'/opt/ssl/key.pem'`, instead of `/opt/ssl/key.pem`. If you want quotes, it should be around the entire list item.

```yaml
version: '3.7'
services:
  zwave2mqtt:
    container_name: zwave2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=<removed>
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=America/Phoenix
      - SSL_KEY=/opt/ssl/key.pem
      - "SSL_CERTIFICATE=/opt/ssl/cert.pem"
    devices:
      - <removed>:/dev/ttyAMA0
    volumes:
      - ./store:/usr/src/app/store
      - /opt/ssl/cert.pem:/opt/ssl/cert.pem
      - /opt/ssl/privkey.pem:/opt/ssl/key.pem
    ports:
      - '8091:8091'
      - '3000:3000'
```

**Comment by asucrews** [comment]
> docker exec zwave2mqtt /bin/bash

i get this error when i try
~/zwave2mqtt $ docker exec zwave2mqtt /bin/bash
OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown

**Comment by asucrews** [comment]
> Remove the quotes around the environment variables. That is causing the files to be named like `'/opt/ssl/key.pem'`, instead of `/opt/ssl/key.pem`. If you want quotes, it should be around the entire list item.
> 
> ```yaml
> version: '3.7'
> services:
>   zwave2mqtt:
>     container_name: zwave2mqtt
>     image: zwavejs/zwavejs2mqtt:latest
>     restart: always
>     tty: true
>     stop_signal: SIGINT
>     environment:
>       - SESSION_SECRET=<removed>
>       - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
>       - TZ=America/Phoenix
>       - SSL_KEY=/opt/ssl/key.pem
>       - "SSL_CERTIFICATE=/opt/ssl/cert.pem"
>     devices:
>       - <removed>:/dev/ttyAMA0
>     volumes:
>       - ./store:/usr/src/app/store
>       - /opt/ssl/cert.pem:/opt/ssl/cert.pem
>       - /opt/ssl/privkey.pem:/opt/ssl/key.pem
>     ports:
>       - '8091:8091'
>       - '3000:3000'
> ```

same results.

**Comment by kpine** [comment]
Working OK for me.

```yaml
    environment:
       - "NO_LOG_COLORS=true"
       - "SSL_KEY=/opt/ssl/key.key"
       - "SSL_CERTIFICATE=/opt/ssl/cert.crt"
    volumes:
      - ./store:/usr/src/app/store
      - ./cert/myserver.crt:/opt/ssl/cert.crt
      - ./cert/myserver.key:/opt/ssl/key.key
```

```text
z2m  | 2022-06-18 21:05:24.082 INFO APP: Version: 6.12.0
z2m  | 2022-06-18 21:05:24.084 INFO APP: Application path:/usr/src/app
z2m  |
z2m  |  ______                       _     ___                  _   _
z2m  | |___  /                      (_)   |__ \                | | | |
z2m  |    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
z2m  |   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
z2m  |  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
z2m  | /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
z2m  |                             _/ |                      | |
z2m  |                            |__/                       |_|
z2m  |
z2m  | 2022-06-18 21:05:24.106 WARN STORE: scenes.json not found
z2m  | 2022-06-18 21:05:24.110 INFO APP: HTTPS is enabled. Loading cert and keys
z2m  | 2022-06-18 21:05:24.130 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTPS
```

```text
$ docker compose exec z2m sh -c 'env | grep SSL'
SSL_CERTIFICATE=/opt/ssl/cert.crt
SSL_KEY=/opt/ssl/key.key
```
