### ISSUE TITLE
[question] Can't activate chimes in multicast

### ISSUE THREAD

**Issue by halomademeapc** [zwave-js/zwavejs2mqtt#2523]
Hello, I got a second ecolink chime that I am trying to set up to ring at the same time as the other one.  If I call this service with either of the entities commented out so there is only one in the list, it works just fine

```yaml
service: zwave_js.multicast_set_value
data:
  command_class: '121'
  value: 12
  property: toneId
target:
  entity_id:
    - siren.living_room_chime
    - siren.master_bedroom_chime
```

however when I have both in the list and change nothing else I get this error
```
ERROR ZWAVE-SERVER: This virtual node does not support the Command Class Sound Switch! (ZW0302)
ZWaveError: This virtual node does not support the Command Class Sound Switch! (ZW0302)
at Object.get (/opt/node_modules/zwave-js/src/lib/node/VirtualEndpoint.ts:107:12)
at VirtualNode.setValue (/opt/node_modules/zwave-js/src/lib/node/VirtualNode.ts:63:13)
at Function.handle (/opt/node_modules/@zwave-js/server/dist/lib/multicast_group/message_handler.js:13:51)
at Object.multicast_group (/opt/node_modules/@zwave-js/server/dist/lib/server.js:41:112)
at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:96:99)
at WebSocket.<anonymous> (/opt/node_modules/@zwave-js/server/dist/lib/server.js:49:45)
at WebSocket.emit (node:events:527:28)
at WebSocket.emit (node:domain:475:12)
at Receiver.receiverOnMessage (/opt/node_modules/@zwave-js/server/node_modules/ws/lib/websocket.js:1169:20)
at Receiver.emit (node:events:527:28)
```

I'm not sure what I'm doing wrong as I had it set up very similarly with some dome chimes before and it worked then.

Thanks for any help
