### ISSUE TITLE
[question] Issue when selecting USB port "by-id" and connecting to Zwave-stick

### ISSUE THREAD

**Issue by ZonPV** [zwave-js/zwavejs2mqtt#2591]
Running Zwavejs2MQTT in latest docker on RPI 4 with Aeotec Z-Stick Gen5 (ZW090).
Running fine for months, since a few days no connection:  Driver: Failed to open the serial port: Error: No such file or directory, cannot open /dev/serial/by-id/usb-0658_0200-if00 **(ZW0100)**
Reboot didn't help. New install of the docker-container either.

This is output of command udevadm:
```
pi@raspberrypi:~/zwavejs2mqtt $ udevadm info -q property -n /dev/serial/by-id/usb-0658_0200-if00
DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4.3/1-1.4.3:1.0/tty/ttyACM0
DEVNAME=/dev/ttyACM0
MAJOR=166
MINOR=0
SUBSYSTEM=tty
USEC_INITIALIZED=8139810
ID_BUS=usb
ID_VENDOR_ID=0658
ID_MODEL_ID=0200
ID_PCI_CLASS_FROM_DATABASE=Serial bus controller
ID_PCI_SUBCLASS_FROM_DATABASE=USB controller
ID_PCI_INTERFACE_FROM_DATABASE=XHCI
ID_VENDOR_FROM_DATABASE=Sigma Designs, Inc.
ID_MODEL_FROM_DATABASE=Aeotec Z-Stick Gen5 (ZW090) - UZB
ID_VENDOR=0658
ID_VENDOR_ENC=0658
ID_MODEL=0200
ID_MODEL_ENC=0200
ID_REVISION=0000
ID_SERIAL=0658_0200
ID_TYPE=generic
ID_USB_INTERFACES=:020201:0a0000:
ID_USB_INTERFACE_NUM=00
ID_USB_DRIVER=cdc_acm
ID_USB_CLASS_FROM_DATABASE=Communications
ID_PATH=platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4.3:1.0
ID_PATH_TAG=platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_4_3_1_0
DEVLINKS=/dev/serial/by-id/usb-0658_0200-if00 /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4.3:1.0
TAGS=:systemd:

```
This is the docker-compose.yml:

```
version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/Amsterdam
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
      # - '/dev/ttyACM0:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```

Did a factory-reset of the Aeotec Z-Stick Gen5 (ZW090).
There is a file named usb-0658_0200-if00 in the path /dev/serial/by-id (created by the host)
Soft reset is off/disabled

In the browser the software says: connected. The textballoon in the browser talks about a ZW100. The stick says it is a ZW090. 

Maybe that is a cause? 

There were no problems in the past.

Any idea's to get the software running again? Thx in advance!

**Comment by kpine** [comment]
> Running fine for months, since a few days no connection: Driver: Failed to open the serial port: Error: No such file or directory, cannot open /dev/serial/by-id/usb-0658_0200-if00 (ZW0100)

That error means your zwavejs2mqtt is configured to use the path `/dev/serial/by-id/usb-0658_0200-if00`. However, your docker compose file shows that you are mapping the USB path into the container as `/dev/zwave`. If that's the case, your zwavejs2mqtt configuration should use `/dev/zwave`, **not** `/dev/serial/by-id/usb-0658_0200-if00`. Based on the provided information, you have a configuration issue.

If the docker compose you posted is not accurate, you'll have to provide the correct docker installation information.

**Comment by ZonPV** [comment]
@kpine Thank you for reply. I saw that solution in another issue. Tried it but did not solve my problem. Sorry I did not mention it.

This is the error: 
Driver: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200) at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:3547:23) at ZWaveController.identify (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:736:33) at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1117:26) at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:924:16) (ZW0100) 

[<a href="https://ibb.co/8g727h3"><img src="https://i.ibb.co/whzCzvH/Zwave-USB-error.jpg" alt="Zwave-USB-error" border="0"></a>](url)

I did not exactly understand your last sentence but here the actual docker-compose.yml:
```
version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/Amsterdam
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```
