### ISSUE TITLE
[Bug]: TypeError: Cannot read property 'toLocaleString' of null

### ISSUE THREAD

**Issue by Aephir** [zwave-js/zwavejs2mqtt#2596]
### Checklist

- [x]  I am not using Home Assistant. Or: a developer has told me to come here. (I am, but this is running only in docker, and this is what is not working)
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.15.2

### ZwaveJS version

?

### Describe the bug

I noticed that the control-panel (`http://local_ip:8091/control-panel`) was down. Looking closer, I see hat the container keeps restarting. The `docker logs zwave2mqtt` is shown under "additional context", but it thows a `TypeError`.

What may or may not be important is that I:

1. Had an unexpected power cut. Nodes did not interview properly after. I needed to power down the computer, remove and re-attach the zwave stick (Aeotec Gen 5), then boot. After that, everything worked as expected.
2. Just ran an rsync backup of my docker persistent storage. Not sure how this would cause problems, but this is the last thing I did on my server before noticing that the zwave2mqtt was not working.

Since I don't know if it's related to any of those, I am not 100 % sure whether this should be a "bug" or a "question/help".

### To Reproduce

1. Set up zwave2mqtt in a docker-compose file with the following (copied almost verbatim from the `docker-compose.yml in this repo`):

```
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET='REDACTED'
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=Europe/Copenhagen
    networks:
      - zwave
    devices:
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
    volumes:
      - /mnt/data/docker/zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
```

2. [Maybe relevant?] Cut power while everything is running, when it never correctly interviews nodes, fix by powering down, removing and attaching the Z-wave stick, then powering up again.

3. [Maybe relevant?] Run rsync, copying the persistent data to a remote storage (NFS mount).

### Expected behavior

* Zwave2mqtt docker container starts up as it normally does
* The zwave2mqtt server is available at `http://host_ip:8091`, like it has always been.
* Docker logs do not report `TypeError: Cannot read property 'toLocaleString' of null`

### Additional context

```
2022-08-16 21:45:09.125 INFO APP: Version: 6.15.2
2022-08-16 21:45:09.128 INFO APP: Application path:/usr/src/app

 ______                       _     ___                  _   _
|___  /                      (_)   |__ \                | | | |
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |
                           |__/                       |_|

2022-08-16 21:45:09.156 WARN STORE: scenes.json not found
TypeError: Cannot read property 'toLocaleString' of null
    at BackupManager.init (/usr/src/app/server/lib/BackupManager.js:68:114)
    at startGateway (/usr/src/app/server/app.js:283:29)
    at startServer (/usr/src/app/server/app.js:219:11)
```
