### ISSUE TITLE
[bug] Fibaro Z-Wave Door / Window Sensor 2 state not exposed to HomeAssistant

### ISSUE THREAD

**Issue by Cyberwizzard** [zwave-js/zwavejs2mqtt#345]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0-beta.0
zwavejs version: 6.0.0 ?

I use the latest Docker image from last week.

### Describe the bug

Fibaro Z-Wave Door / Window Sensor 2 does not expose state to HomeAssistant.

The state seems to be detected by the ZWaveJS2MQTT but for some reason does not show up in HA.

### To Reproduce

1. Pair a Fibaro Door Sensor 2 to the Z-Wave network
2. Go to Home Assistant > Developer Tools > Entity: sensor.nodeid_13_notification_access_control_door_state
2. Look at data: no status entry present
3. Go to ZWaveJS2MQTT webgui, enable debug logging
4. Open and close door, see state updates in the log just fine

### Expected behavior

Expect the door state to be visible and toggling in HomeAssistant.

### Additional context

Status report within HomeAssistant Developer panel for the entity:
```
id: 13-113-0-Access Control-Door state
nodeId: 13
commandClass: 113
commandClassName: Notification
endpoint: 0
property: Access Control
propertyName: Access Control
propertyKey: Door state
type: number
readable: true
writeable: false
label: Door state
stateless: false
ccSpecific:
  notificationType: 6
min: 0
max: 255
list: true
states:
  - text: Window/door is open
    value: 22
  - text: Window/door is closed
    value: 23
lastUpdate: 1611346323184
nodeName: ''
nodeLocation: ''
friendly_name: Poort State
icon: 'mdi:alarm-light'
```

Debug log within the web-gui of ZWaveJS2MQTT:
```
2021-01-25 19:25:53.055 INFO ZWAVE: Node 13: value updated: 113-0-Access Control-Door state 23 => 22
2021-01-25 19:26:00.626 INFO ZWAVE: Node 13: value updated: 113-0-Access Control-Door state 22 => 23
2021-01-25 19:26:05.461 INFO ZWAVE: Node 13: value updated: 113-0-Access Control-Door state 23 => 22
```
