### ISSUE TITLE
[feat] Add MQTT Scene, so it is discovery by HASS

### ISSUE THREAD

**Issue by fanningert** [zwave-js/zwavejs2mqtt#387]
**Is your feature request related to a problem? Please describe.**
I created under zwavejs2mqtt a new scene. This scene is not visible under mqtt (checked with MQTT Explorer) and also not visible and executeable under HASS.

**Describe the solution you'd like**
Add created scenes to mqtt.
**https://www.home-assistant.io/integrations/scene.mqtt/**

**Comment by robertsLando** [comment]
You can trigger the scene using mqtt apis :)

**Comment by fanningert** [comment]
@robertsLando where can I find the information abput the command_topic. In the application mqtt_explorer I was not able to find the entry.

**Comment by fanningert** [comment]
@robertsLando Thank you for your hint.

Here is the infos for all who also searching for the solution.

In my case the scene is having the number `1`, the mqtt-prefix is `homeassistant` and the name of my gatway is `HomeAssistant`.
For the Home Assistant integration I created a switch with following entries in the `configuration.yaml`.
```yaml
switch:
  - platform: mqtt
    name: Doorbell Scene
    unique_id: zwavedoorbellscene
    command_topic: "homeassistant/_CLIENTS/ZWAVE_GATEWAY-HomeAssistant/api/_activateScene/set"
    payload_on: '{ "args": [ 1 ] }'
```

Details: https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=apis
