### ISSUE TITLE
[bug] Scenes retriggers after zwavejs2mqtt restart

### ISSUE THREAD

**Issue by haavardNO** [zwave-js/zwavejs2mqtt#434]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version 1.0.1

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

### Describe the bug

As discussed with @robertsLando I am creating a separate issue.
When restarting the application Home Assistant will re-trigger a scene, and in my case open my garage. 
Looks as the "0" state is set back after restart, and this is what is used as trigger.
I think the zwave2mqtt version used "inactive" as the default state, and changed it to 0 only when triggered, then back to inactive. Maybe this could solve the issue?

![106652427-bcfa8800-6595-11eb-94cd-da35436c8d84](https://user-images.githubusercontent.com/27728530/106734550-70ee2880-6613-11eb-8eef-bf49723251fd.png)

### To Reproduce
I have this issue with a fibaro keyfob that is used as a scene controller. I have the following automation in HA

```
alias: Garage open keyfob
description: Open garage from keyfob
trigger:
  - platform: state
    entity_id: sensor.garage_keyfob_scene_state_004_scene
    to: '0'
condition: []
action:
  - service: script.garage_open_if_closed
    data: {}
mode: single

```

**Comment by robertsLando** [comment]
@haavardNO Fix ready

**Comment by haavardNO** [comment]
Tried with the latest version now. 1.0.5, and there is still something strange going on.

Below is a screen capture from home assistant before I restart zwavejs2mqtt:
<img width="488" alt="Skjermbilde 2021-02-04 kl  19 55 31" src="https://user-images.githubusercontent.com/27728530/106943540-d92d2f00-6725-11eb-9a95-ebe5dac29aa7.png">

Then I delete everything in mqtt explorer that contains keyfob, and get the following in HA:
<img width="497" alt="Skjermbilde 2021-02-04 kl  20 00 07" src="https://user-images.githubusercontent.com/27728530/106944248-a46da780-6726-11eb-850b-d7c4ae988d91.png">

Then when I restart the docker image states are again inserted as below:
<img width="502" alt="Skjermbilde 2021-02-04 kl  20 13 46" src="https://user-images.githubusercontent.com/27728530/106945316-f06d1c00-6727-11eb-845a-e1c0f5fa1c75.png">

Any suggestions what is happening here?

**Comment by haavardNO** [comment]
Also, just as a reference I use the settings below:
![Skjermbilde 2021-02-04 kl  20 35 12](https://user-images.githubusercontent.com/27728530/106945798-8dc85000-6728-11eb-9b99-5927334124f7.png)

![Skjermbilde 2021-02-04 kl  20 35 30](https://user-images.githubusercontent.com/27728530/106945819-93259a80-6728-11eb-8e74-53c537da5637.png)

**Comment by robertsLando** [comment]
> Any suggestions what is happening here?

Did you delete all retained messages from mqtt broker right?

@billiaz Could you help in this?

**Comment by billiaz** [comment]
Let me check if my Scenes retain of course I can!

**Comment by billiaz** [comment]
@robertsLando I do see these getting retained on my broker too

**Comment by billiaz** [comment]
@haavardNO state 0 means inactive right? should this be empty? I see MQTT refreshes value and cleans it after 1 second but the payload is there without value.

Looking into my Button from Aeotec I have this

```json
{
  "type": "sensor",
  "object_id": "scene_state_scene_001",
  "discovery_payload": {
    "state_topic": "zwave2mqtt/MasterBedroom/VassilisSwitch/91/0/scene/001",
    "value_template": "{{ value_json.value}}",
    "json_attributes_topic": "zwave2mqtt/MasterBedroom/VassilisSwitch/91/0/scene/001",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xcddb486e_node60"
      ],
      "manufacturer": "Aeotec Ltd.",
      "model": "NanoMote Quad (Aeotec NanoMote Quad)",
      "name": "MasterBedroom-VassilisSwitch",
      "sw_version": "1.2"
    },
    "name": "MasterBedroom-VassilisSwitch Scene 001",
    "unique_id": "zwavejs2mqtt_0xcddb486e_60-91-0-scene-001"
  },
  "discoveryTopic": "sensor/MasterBedroom-VassilisSwitch/scene_state_scene_001/config",
  "values": [
    "91-0-scene-001"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_scene_state_scene_001"
}
```

most probably this:     `"value_template": "{{ value_json.value}}",` returns the 0

can you share with us your node export and also the specific MQTT payload under the device?

**Comment by haavardNO** [comment]
state 0 means button press. So the system triggers on state 0.
When I press the button the 0 state disappears after a short while. 

```
id: 71-91-0-scene-004
nodeId: 71
commandClass: 91
commandClassName: Central Scene
endpoint: 0
property: scene
propertyName: scene
propertyKey: '004'
propertyKeyName: '004'
type: number
readable: true
writeable: false
label: Scene 004
stateless: false
min: 0
max: 255
list: true
states:
  - text: KeyPressed
    value: 0
  - text: KeyReleased
    value: 1
  - text: KeyHeldDown
    value: 2
  - text: KeyPressed2x
    value: 3
  - text: KeyPressed3x
    value: 4
value: 0
lastUpdate: 1612465964173
friendly_name: garage-keyfob_scene_state_004_scene

```
