### ISSUE TITLE
[question] Network Graph is a flat line

### ISSUE THREAD

**Issue by bushvin** [zwave-js/zwavejs2mqtt#739]
I have recently adopted ZwaveJS2MQTT, and everything seems to work.

I took the time to perform cleanups, as previous Zwave Control Panels lacked some cleanup features.

My network Graph is a flat line with the controller to the left (in the right purple colour) and all other nodes to the right in grey.
Grey seems to indicate they are not connected, however I can assure you they are, as I can control my nodes

I have not checked all nodes, but those I did, did have 'neighbors' (in the debug section of a node).

I have attached the debug info of my Zwave controller (a Z-Wave.ME UZB) and one of the nodes for reference.

[controller.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6041487/controller.json.txt)
[node-006.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6041490/node-006.json.txt)

I have tested it on Firefox v85.0.1  and Chromium v88.0.4324.150

Any pointers?

**Comment by robertsLando** [comment]
Could you also attach a screenshot?

**Comment by bushvin** [comment]
![detail](https://user-images.githubusercontent.com/4785760/109130530-206d7500-7752-11eb-826f-59ea4a31769d.png)
![overview](https://user-images.githubusercontent.com/4785760/109130534-21060b80-7752-11eb-8b34-5ad12bded3d8.png)
Here you go

**Comment by robertsLando** [comment]
@bushvin While you have browser open try to press F12 (chrome) and check if there are errors on console. If so send me a screenshot or the logs you find there

**Comment by bushvin** [comment]
There are no messages whatsoever. 
I should have mentioned that I made sure there were none. Apologies.

**Comment by robertsLando** [comment]
Hummm strange. I would need a nodes dump so, you could use mqtt apis and require `getNodes` api https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=apis

**Comment by bushvin** [comment]
I'm afraid that doesn't seem to get any result except for a 404
![API](https://user-images.githubusercontent.com/4785760/109145922-74348a00-7763-11eb-8c48-54cd3b087068.png)

I got the MQTT name from the settings page
![MQTT_name](https://user-images.githubusercontent.com/4785760/109146223-d4c3c700-7763-11eb-82ed-e57b459e1405.png)

**Comment by robertsLando** [comment]
@bushvin Sorry maybe I didn't explained it well, that needs to be called using MQTT

**Comment by bushvin** [comment]
Ah... my bad... :/

For future reference these were the commands executed:

**To log to file:**
`mosquitto_sub -h mosquitto -p 1883 -u zwavejs2mqtt -P ******** -t 'zwave/#' -d |tee -a zwavejs@mqtt.log` 

**To send the command:**
`mosquitto_pub -h mosquitto -p 1883 -u zwavejs2mqtt -P ******** -t 'zwave/_CLIENTS/ZWAVE_GATEWAY-zwavejs2mqtt/api/getNodes/set' -m "{args: []}"`

[zwavejs@mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6043193/zwavejs%40mqtt.log)

**Comment by robertsLando** [comment]
@bushvin How are you building z2m? Git clone?

**Comment by bushvin** [comment]
not building, running it in Docker

```yml
---
version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:1.2.3
    restart: always
    tty: true
    stop_signal: SIGINT
    networks:
      - zwavejs
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - zwavejs_store:/usr/src/app/store
    ports:
      - '8091:8091'
networks:
  zwavejs:
volumes:
  zwavejs_store:
```
