### ISSUE TITLE
How to configure HTTPS access with Docker [question] 

### ISSUE THREAD

**Issue by cts1085** [zwave-js/zwavejs2mqtt#748]
I have attempted a few different ways to get the openssl running in a docker container so that accessing the UI from HA (which currently is accessed via HTTPS) works...  I am using a YML file with docker-compose and I just can't seem to get the right combination of environment variables and cert locations.  

I have the certs located on PI in /ssl and i have tried mapping that to /ssl and /etc/ssl/private with no luck.

When I set HTTPS='true' it seems to keep restarting the container.

is there any guidance on turning on this feature?

My current YML with options commented out is:

```
version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
#    image: zwavejs/zwavejs2mqtt:latest
    image: zwavejs/zwavejs2mqtt:master
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    hostname: HHHHH
    domainname: DDDDD.com
    environment:
      - TZ=America/New_York
#      - HTTPS='true'
#      - HOST=HHHHH.DDDDD.com
      - PORT=8091
#      - SSL_KEY=/ssl/privkey.pem
#      - SSL_CERTIFICATE=/ssl/cert.pem
    networks:
      - zwave
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - ./store:/usr/src/app/store
      - /ssl:/etc/ssl/private
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server
networks:
  zwave:
# volumes:
#   zwavejs2mqtt:
#     name: zwavejs2mqtt

```
