### ISSUE TITLE
[question] Enrollment codes for BeNext/Zipato Keypad

### ISSUE THREAD

**Issue by lolautruche** [zwave-js/zwavejs2mqtt#782]
Hello

Sorry in advance if this question has already been posted/answered.
I have a BeNext/Zipat mini-keypad that I used to use with Domoticz/OZW. I am now using ZWaveJS2mqtt with HomeAssistant, and I'd like to use my tags. I can see in the UI that I can manually add user codes (most likely including the tags codes), but I can't figure out how to enroll my tags. I tried to press home/away on my tag reader using debug, but the code won't appear here.
I currently don't have a compatible NFC reader, but would buy one if needed.

Can you please help me?

Thanks in advance

**Comment by robertsLando** [comment]
@lolautruche Could you attach a gif showing what you are actually try to do on the UI and also both z2m and zwavejs logs?

**Comment by lolautruche** [comment]
Hi @robertsLando 

On the UI, I couldn't figure out how to do or what value to inject in the "user codes" section.

I checked if the user code from my badge would appear in the logs but I had no luck.

Here are the logs from z2m:

```
2021-03-02 13:58:55.232 INFO ZWAVE: Node 3: value updated: 112-0-4 1 => 1
2021-03-02 13:59:02.853 DEBUG MQTT: Publishing to zwave/Keypad/99/0/userIdStatus: { time: 1614693542852, value: 0 } with options { qos: 1, retain: true }
2021-03-02 13:59:02.854 INFO ZWAVE: Node 25: value updated: 99-0-userIdStatus-0 0 => 0
2021-03-02 13:59:02.857 DEBUG MQTT: Publishing to zwave/Keypad/99/0/userCode: { time: 1614693542856, value: <Buffer 8f 1f 35 ad 29 00 01 04> } with options { qos: 1, retain: true }
2021-03-0
```

With another badge:

```
2021-03-02 14:04:24.089 DEBUG MQTT: Publishing to zwave/Keypad/99/0/userIdStatus: { time: 1614693864088, value: 0 } with options { qos: 1, retain: true }
2021-03-02 14:04:24.090 INFO ZWAVE: Node 25: value updated: 99-0-userIdStatus-0 0 => 0
2021-03-02 14:04:24.092 DEBUG MQTT: Publishing to zwave/Keypad/99/0/userCode: { time: 1614693864091, value: <Buffer 8f 05 e3 87 27 00 01 04> } with options { qos: 1, retain: true }
2021-03-02 14:04:24.093 INFO ZWAVE: Node 25: value updated: 99-0-userCode-0 ��' => ��'
```

Please note that I included the tag reader with secure inclusion.

The zwavejs log doesn't have relevant information:

```
13:59:02.870 CNTRLR « [Node 025] received wakeup notification
14:04:24.109 CNTRLR « [Node 025] received wakeup notification
```

**Comment by robertsLando** [comment]
@lolautruche Please attach to your issue all logs needed: https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=bug-report

> but I can't figure out how to enroll my tags. I tried to press home/away on my tag reader using debug, but the code won't appear here

I never used those devices but I think a manual would be useful in this case. BTW @AlCalzone said to me that other users having the same devices had no issues using them

**Comment by lolautruche** [comment]
[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6069327/zwavejs_1.log)
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6069328/zwavejs2mqtt.log)

**Comment by lolautruche** [comment]
If others can use it, then I'm pretty sure I can :-)
It's just that I don't understand how I can add the code of my badges as I don't know them, unfortunately. And I'm not sure what value to add (I'm suspecting this should be hex value)

**Comment by robertsLando** [comment]
@lolautruche What version are you using? Could you update to latest please? 2.1.0 ATM

**Comment by AlCalzone** [comment]
> zwavejs_1.log

That's not loglevel debug nor silly 🤷🏻‍♂️ 

Afaik the new codes should appear as user code 0 or something and you have to manually copy them to another user code where you want to use them.

**Comment by lolautruche** [comment]
Oh my... Sorry, I was convinced that I set it to debug. Let me try again :-)

**Comment by lolautruche** [comment]
@robertsLando 
<img width="825" alt="Capture d’écran 2021-03-02 à 15 36 47" src="https://user-images.githubusercontent.com/313528/109664184-2d80ce80-7b6d-11eb-9296-b8ce5daa0b3a.png">

I did a `docker-compose pull` this morning.

**Comment by robertsLando** [comment]
app version 1.0.5, latest is 2.1.0, I think something isn't wrong in your docker compose, what tag are you using? latest?

**Comment by lolautruche** [comment]
Weird...
I'm indeed using the `latest` tag.
Here is my `docker-compose.yml`

```yaml
version: "3"
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/lolautruche/homeassistant/config:/config
    devices: []
      #- '/dev/ttyUSB0:/dev/ttyUSB0'
      #- /dev/ttyUSB1:/dev/ttyUSB1
      #- /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    network_mode: host

  zwavejs2mqtt:
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    #networks:
    #  - zwave
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - ./zwavejs/store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    restart: unless-stopped
    volumes:
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log

  portainer:
    image: portainer/portainer-ce
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000
    restart: unless-stopped

volumes:
  portainer_data:
```
