### ISSUE TITLE
[feat] Run Docker container as non-root user

### ISSUE THREAD

**Issue by Laynezilla** [zwave-js/zwavejs2mqtt#783]
**Is your feature request related to a problem? Please describe.**
The Docker container is currently running as root which is a security issue.

**Describe the solution you'd like**
Have environmental variables specify UID and GID similar to [this](https://github.com/linuxserver/docker-homeassistant#parameters).

**Describe alternatives you've considered**
Hardcode user 1001 or something similar to [this](https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html).

**Additional context**
Thanks for the great software!

**Comment by robertsLando** [comment]
@Laynezilla Would you like to submit a PR for this?

**Comment by Laynezilla** [comment]
> @Laynezilla Would you like to submit a PR for this?

I don't have time at the moment to work on this but I can give it a shot at some point. Also, I don't have any coding background, only tinkering, so if anyone else wants to attempt that might be better haha.

**Comment by ChrisRomp** [comment]
The way that linuxserver.io handles it is they run everything in their container as user:group `abc:abc`.  When starting a container they look for the `PUID` and `PGID` to set the `abc` user/group to.

The Docker Node image, which is the base for this image, provides some [guidance](https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user) for running as non-root.

I'll play around with the Dockerfile locally and see if I can get it to run under the `node` user instead of `root`, and then assign a custom `PUID/PGID` to `node`.  If I get that working I'll submit a PR, but additional testing should be done to ensure it won't break anything else.

**Comment by ChrisRomp** [comment]
There's a bit of overhead to how linuxserver.io does it. I've done some experimentation and without adding more "things" to the base image I haven't found a good way to do this.

In a nutshell, what needs to happen at container start is:
1. Modify user and group ID for the `node` user
2. `chown -R node:node /usr/src/app`  
    - This takes too long - probably because of `node_modules`
3. Run `node bin/www` from the `/usr/src/app` directory

The fastest/easiest solution for this is to just run under the existing `node` user, which as a UID/GID of 1000.  This can be handled in the `Dockerfile` by copying the files as `node:node` and then setting `USER node` before executing the app.  I'll submit a PR referencing this issue.

I've run the container and it looks like it's ok, but I haven't tested it with a controller attached.

**Comment by scyto** [comment]
please don't do this by default, let it be configured if folks want, just not by default - its a PITA on many docker platforms (thinking synology here)

linuxserver:io containers are needlessly complex and fragile, i wouldn't hold them up as a good example of creating containers

**Comment by scyto** [comment]
oh and only privileged containers are actually root, the security aspect of running as root insider a container is overblown outside of that mode

**Comment by ChrisRomp** [comment]
@scyto This issue is long closed. I think you're safe. :)

**Comment by ChrisRomp** [comment]
Or I guess the PR is closed. Not sure why the issue is still open if the devs don't want to do it.

**Comment by scyto** [comment]
> Or I guess the PR is closed. Not sure why the issue is still open if the devs don't want to do it.

it was closed by the bot due to inactivity

**Comment by ftc2** [comment]
i was surprised to see this running as root. uh, wat???

anyway, i worked around it by adding this to the service definition in compose:

```yaml
user: "${PUID}:${PGID}"
group_add:
  - audio
```

this runs node as PUID:GUID (i do `2000:2000`) and adds that user to the `audio` group inside the container. the group is necessary to access `/dev/zwave`.

for completeness, here is my solution for rootless HA + zwave-js-ui that i wish i had this morning:

`.env`:
```bash
TZ=US/Eastern
RESTART_POLICY=unless-stopped

PUID=2000
PGID=2000

# home-assistant
HA_PROXY_HOST=homeassistant.example.com

# zwave-js-ui
SESSION_SECRET=foo
```

`docker-compose.yml`:
```yaml
services:
  home_assistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: home_assistant
    restart: ${RESTART_POLICY}
    networks:
      - wan
      - traefik_home_assistant
    # ports:
    #   - "8123:8123" # webui
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ./ha_conf/:/config/
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_home_assistant"
      - "traefik.http.services.home_assistant.loadbalancer.server.port=8123"
      #
      - "traefik.http.routers.home_assistant.rule=Host(`${HA_PROXY_HOST}`)"

  zwave_js:
    image: zwavejs/zwave-js-ui
    container_name: zwave_js
    restart: ${RESTART_POLICY}
    user: "${PUID}:${PGID}"
    group_add:
      - audio
    tty: true
    stop_signal: SIGINT
    networks:
      - wan
    ports:
      - "8091:8091" # webui
    healthcheck:
      test: 'wget --no-verbose --spider --no-check-certificate --header "Accept: text/plain" http://localhost:8091/health || exit 1'
      interval: 1m
      timeout: 10s
      start_period: 30s
      retries: 3
    environment:
      - TZ
      - SESSION_SECRET
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
    devices:
      - /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00:/dev/zwave
    volumes:
      - ./zwave_js_conf/:/usr/src/app/store/

networks:
  wan:
  traefik_home_assistant: # docker network create --internal traefik_home_assistant
    external: true
```

n.b.

`chown` zwave-js' conf dir as needed

also, to make traefik work, add this to HA's `configuration.yaml`
```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0 # disable the security check, lol
```
