### ISSUE TITLE
[question] Stuck on "Loading"

### ISSUE THREAD

**Issue by Isilorn** [zwave-js/zwavejs2mqtt#918]
Hello,

I've created zwavejs2mqtt container and the web page is stuck on "loading" when I access it.

Here is my docker-compose file :

```
version: "3"
services:
  zwave2mqtt:
    image: zwavejs/zwavejs2mqtt:latest
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=xxx
      - TZ=Europe/Paris
    networks:
      - DockerNet
    container_name: Zwave2mqtt
    devices:
      - "/dev/Zstick2:/dev/ttyACM0"
    volumes:
      - /home/docker/Zwave2MQTT/data:/usr/src/app/store
    ports:
      - 8091:8091
      - 3000:3000
    restart: always
    labels:
      - autoheal=false

networks:
  DockerNet:
    external: true
```

(the /dev/Zstick2 is a device created via a Udev rule file)

Some files are created within the data folder :

```
root@phoenix:/home/docker/Zwave2MQTT/data# ls -la
total 16
drwxr-xr-x 2 root root  4096 Mar 20 09:46 .
drwxr-xr-x 3 plex media 4096 Mar 20 09:45 ..
-rw-r--r-- 1 root root   146 Mar 20 09:46 FLcyMZdJFturL8yzxTXZIqWkH-DgVgic.json
-rw-r--r-- 1 root root   186 Mar 19 17:48 users.json
```

Any clue ?

Thanks
